In [1]:
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt
import math

In [2]:
A = np.zeros((30,6))

In [3]:
#Points from image pic1grey300.jpg
A=([[206., 104., 1., 0., 0., 0.],
       [0., 0., 0., 206., 104., 1.],
       [204., 117., 1., 0., 0., 0.],
       [0., 0., 0., 204., 117., 1.],
       [191., 117., 1., 0., 0., 0.],
       [0., 0., 0., 191., 117., 1.],
       [75., 88., 1., 0., 0., 0.],
       [0., 0., 0., 75., 88., 1.],
       [78., 89., 1., 0., 0., 0.],
       [0., 0., 0., 78., 89., 1.],
       [69., 95., 1., 0., 0., 0.],
       [0., 0., 0., 69., 95., 1.],
       [67., 96., 1., 0., 0., 0.],
       [0., 0., 0., 67., 96., 1.],
       [87., 96., 1., 0., 0., 0.],
       [0., 0., 0., 87., 96., 1.],
       [87., 98., 1., 0., 0., 0.],
       [0., 0., 0., 87., 98., 1.],
       [200., 214., 1., 0., 0., 0.],
       [0., 0., 0., 200., 214., 1.],
       [211., 215., 1., 0., 0., 0.],
       [0., 0., 0., 211., 215., 1.],
       [272., 116., 1., 0., 0., 0.],
       [0., 0., 0., 272., 116., 1.],
       [195., 78., 1., 0., 0., 0.],
       [0., 0., 0., 195., 78., 1.],
       [257., 59., 1., 0., 0., 0.],
       [0., 0., 0., 257., 59., 1.],
       [109., 175., 1., 0., 0., 0.],
       [0., 0., 0., 109., 175., 1.]])

In [4]:
B = np.zeros((30,1))

In [5]:
#matching corner points in pic2grey300.jpg
B=([[182.],
       [74.],
       [182.],
       [90.],
       [165.],
       [91.],
       [16.],
       [70.],
       [20.],
       [71.],
       [9.],
       [80.],
       [7.],
       [81.],
       [31.],
       [79.],
       [31.],
       [81.],
       [191.],
       [211.],
       [204.],
       [211.],
       [267.],
       [79.],
       [165.],
       [42.],
       [240.],
       [10.],
       [70.],
       [176.]])

In [6]:
Ac = A.copy()
Bc = B.copy()

In [7]:
acc = np.array(Ac)
acct = acc.transpose(1, 0) 
print(acct.shape)
print(acc.shape)
print(acct)

(6, 30)
(30, 6)
[[206.   0. 204.   0. 191.   0.  75.   0.  78.   0.  69.   0.  67.   0.
   87.   0.  87.   0. 200.   0. 211.   0. 272.   0. 195.   0. 257.   0.
  109.   0.]
 [104.   0. 117.   0. 117.   0.  88.   0.  89.   0.  95.   0.  96.   0.
   96.   0.  98.   0. 214.   0. 215.   0. 116.   0.  78.   0.  59.   0.
  175.   0.]
 [  1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.
    1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.
    1.   0.]
 [  0. 206.   0. 204.   0. 191.   0.  75.   0.  78.   0.  69.   0.  67.
    0.  87.   0.  87.   0. 200.   0. 211.   0. 272.   0. 195.   0. 257.
    0. 109.]
 [  0. 104.   0. 117.   0. 117.   0.  88.   0.  89.   0.  95.   0.  96.
    0.  96.   0.  98.   0. 214.   0. 215.   0. 116.   0.  78.   0.  59.
    0. 175.]
 [  0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.
    0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.   0.   1.
    0.   1.]]


In [8]:
bcc = np.array(Bc)

In [9]:
ATA  = np.dot(acct, acc)
print(ATA)

[[4.31090e+05 2.80211e+05 2.30800e+03 0.00000e+00 0.00000e+00 0.00000e+00]
 [2.80211e+05 2.36587e+05 1.75700e+03 0.00000e+00 0.00000e+00 0.00000e+00]
 [2.30800e+03 1.75700e+03 1.50000e+01 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 4.31090e+05 2.80211e+05 2.30800e+03]
 [0.00000e+00 0.00000e+00 0.00000e+00 2.80211e+05 2.36587e+05 1.75700e+03]
 [0.00000e+00 0.00000e+00 0.00000e+00 2.30800e+03 1.75700e+03 1.50000e+01]]


In [10]:
Ainv = np.linalg.inv(ATA)
print(Ainv)

[[ 1.37357113e-05 -4.40277742e-06 -1.59775611e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.40277742e-06  3.38959335e-05 -3.29290300e-03  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.59775611e-03 -3.29290300e-03  6.98216778e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.37357113e-05
  -4.40277742e-06 -1.59775611e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.40277742e-06
   3.38959335e-05 -3.29290300e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.59775611e-03
  -3.29290300e-03  6.98216778e-01]]


In [11]:
ATB = np.dot(acct,bcc)
print(ATB)

[[370732.]
 [225242.]
 [  1780.]
 [224793.]
 [206599.]
 [  1446.]]


In [12]:
#Affine transformation matrix
x = np.dot(Ainv,ATB)
print(x)

[[  1.25657144]
 [  0.14117005]
 [-91.21351059]
 [ -0.13227301]
 [  1.2516147 ]
 [-29.85339471]]


Therefore the Affine Transformation Matrix = 
[[1.25657144,0.14117005,-91.21351059],
[-0.13227301, 1.2516147, -29.85339471]]